name: Build and deploy MessianicChords

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
# If this workflow is already running, cancel it.
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
            
      - name: Run NPM install and build
        env:
          CI: true
        run: |
          cd src\ClientApp
          npm install
          npm run build
          cd ..
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
          
      - name: Build with dotnet
        run: dotnet build --configuration Release
          
      - name: Write publish profile to directory
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: ${{ env.home }}/MessianicChordsOnVm.pubxml
          contents: |
            ${{ secrets.PUBLISH_PROFILE }}
          write-mode: overwrite
          
      - name: Dump workspace directory
        run: echo ${{ github.workspace }}

      - name: dotnet publish
        run: dotnet publish -c Release -o Publish /p:PublishProfileFullPath=${{ env.home }}/MessianicChordsOnVm.pubxml
